[package]
name = "randmst"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
fastrand = "1.9.0"
itertools = "0.10.5"
rand = "0.8"
rand_distr = "0.4.3"
rayon = "1.6"
smallvec = "1.10.0"
